import { notFound } from "next/navigation"
import { OrderForm } from "@/components/order-form"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import {
  Utensils, Coffee, ChefHat, UtensilsCrossed,
  Dumbbell, PersonStanding, Leaf, Rocket,
  Shield, Code, Camera, Sparkles, Palette,
  TrendingUp, Users, Scale, Lightbulb, ShoppingBag
} from "lucide-react"

const templates: Record<string, {
  id: string
  name: string
  industry: string
  price: string
  originalPrice: string
  description: string
  includes: string[]
  icon: React.ElementType
  color: string
  themes: string[]
  requiresPayment?: boolean
  paymentNote?: string
}> = {
  restaurant: {
    id: "restaurant",
    name: "The Grand Table",
    industry: "Restaurant",
    price: "$997",
    originalPrice: "$1,297",
    description: "A stunning restaurant website with online reservations, full menu display, photo gallery, and contact forms.",
    includes: [
      "Full custom setup with your branding",
      "Menu display with your items",
      "Online reservation form",
      "Photo gallery",
      "Location & hours",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Utensils,
    color: "from-orange-500/20 to-red-500/20",
    themes: ["Warm & Rustic", "Modern & Minimal", "Fresh & Vibrant", "Bold & Dramatic"],
  },
  cafe: {
    id: "cafe",
    name: "Brew & Bloom",
    industry: "Café",
    price: "$799",
    originalPrice: "$1,099",
    description: "Cozy café site with seasonal menu, events calendar, and online ordering setup.",
    includes: [
      "Full custom setup with your branding",
      "Seasonal menu display",
      "Events calendar",
      "Photo gallery",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Coffee,
    color: "from-amber-500/20 to-yellow-500/20",
    themes: ["Warm & Cozy", "Modern & Clean", "Fresh & Bright", "Bold & Vibrant"],
  },
  chef: {
    id: "chef",
    name: "Chef's Table",
    industry: "Personal Chef",
    price: "$997",
    originalPrice: "$1,297",
    description: "Sophisticated personal chef portfolio with booking system and menu showcase.",
    requiresPayment: true,
    paymentNote: "Payment setup is included — connects your Stripe account to take deposits",
    includes: [
      "Full custom setup with your branding",
      "Chef portfolio & bio",
      "Menu showcase",
      "Booking form",
      "Stripe deposit integration ✓",
      "Client testimonials",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: ChefHat,
    color: "from-green-500/20 to-emerald-500/20",
    themes: ["Classic Elegant", "Modern Minimal", "Warm & Rustic", "Bold & Dark"],
  },
  catering: {
    id: "catering",
    name: "Feast & Co",
    industry: "Catering",
    price: "$997",
    originalPrice: "$1,297",
    description: "Professional catering company site with service packages and inquiry form.",
    requiresPayment: true,
    paymentNote: "Payment setup is included — connects your Stripe account to take deposits",
    includes: [
      "Full custom setup with your branding",
      "Service packages display",
      "Photo gallery",
      "Inquiry form",
      "Stripe deposit integration ✓",
      "Pricing display",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: UtensilsCrossed,
    color: "from-rose-500/20 to-pink-500/20",
    themes: ["Warm & Elegant", "Modern & Clean", "Fresh & Bright", "Bold & Dark"],
  },
  gym: {
    id: "gym",
    name: "Iron & Grit",
    industry: "Gym & Fitness",
    price: "$997",
    originalPrice: "$1,297",
    description: "High-energy gym site with class schedule, membership plans, trainer profiles, and BMI calculator.",
    requiresPayment: true,
    paymentNote: "Payment setup is included — connects your Stripe account to membership plans",
    includes: [
      "Full custom setup with your branding",
      "Class schedule display",
      "Membership plans",
      "Trainer profiles",
      "BMI & calorie calculator",
      "Online class booking",
      "Stripe payment integration ✓",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Dumbbell,
    color: "from-green-500/20 to-emerald-500/20",
    themes: ["Dark & Powerful", "Bold & Energetic", "Clean & Modern", "Premium & Sleek"],
  },
  trainer: {
    id: "trainer",
    name: "Peak Performance",
    industry: "Personal Trainer",
    price: "$997",
    originalPrice: "$1,297",
    description: "Personal trainer site with transformation gallery and online booking.",
    requiresPayment: true,
    paymentNote: "Payment setup is included — connects your Stripe account to session bookings",
    includes: [
      "Full custom setup with your branding",
      "Trainer bio & credentials",
      "Program packages",
      "Transformation gallery",
      "Booking form",
      "Stripe payment integration ✓",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: PersonStanding,
    color: "from-blue-500/20 to-indigo-500/20",
    themes: ["Dark & Bold", "Clean & Modern", "Energy & Vibrant", "Premium & Sleek"],
  },
  yoga: {
    id: "yoga",
    name: "Flow State",
    industry: "Yoga & Wellness",
    price: "$799",
    originalPrice: "$1,099",
    description: "Calming yoga studio with class bookings and instructor profiles.",
    includes: [
      "Full custom setup with your branding",
      "Class schedule",
      "Instructor profiles",
      "Booking system",
      "Wellness blog",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Leaf,
    color: "from-teal-500/20 to-cyan-500/20",
    themes: ["Calm & Natural", "Modern & Minimal", "Fresh & Bright", "Warm & Earthy"],
  },
  saas: {
    id: "saas",
    name: "Nexus",
    industry: "SaaS",
    price: "$1,097",
    originalPrice: "$1,397",
    description: "Modern SaaS landing page with pricing, features, integrations showcase, and demo request form.",
    requiresPayment: true,
    paymentNote: "Payment setup is included — connects your Stripe account to subscription plans",
    includes: [
      "Full custom setup with your branding",
      "Feature showcase",
      "Pricing tiers",
      "Integration logos",
      "Demo request form",
      "Contact form",
      "Stripe subscription integration ✓",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Rocket,
    color: "from-violet-500/20 to-purple-500/20",
    themes: ["Deep Space", "Midnight Luxury", "Carbon Tech", "Pure Minimal"],
  },
  security: {
    id: "security",
    name: "SecureStack",
    industry: "Cybersecurity",
    price: "$1,097",
    originalPrice: "$1,397",
    description: "Trust-building cybersecurity firm site with services and case studies.",
    includes: [
      "Full custom setup with your branding",
      "Services showcase",
      "Case studies",
      "Trust badges",
      "Team profiles",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Shield,
    color: "from-green-500/20 to-emerald-500/20",
    themes: ["Dark & Professional", "Clean & Modern", "Bold & Confident", "Minimal & Sharp"],
  },
  software: {
    id: "software",
    name: "AppForge",
    industry: "Software / App Dev",
    price: "$1,097",
    originalPrice: "$1,397",
    description: "Software company site with product showcase, team profiles, and pricing plans.",
    includes: [
      "Full custom setup with your branding",
      "Product showcase",
      "Team profiles",
      "Portfolio section",
      "Pricing plans",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Code,
    color: "from-blue-500/20 to-sky-500/20",
    themes: ["Dark & Tech", "Clean & Modern", "Bold & Vibrant", "Minimal & Sharp"],
  },
  photography: {
    id: "photography",
    name: "Lens & Light",
    industry: "Photographer",
    price: "$799",
    originalPrice: "$1,099",
    description: "Stunning photography portfolio with galleries, booking, and testimonials.",
    includes: [
      "Full custom setup with your branding",
      "Gallery with lightbox",
      "About me section",
      "Services page",
      "Booking form",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Camera,
    color: "from-amber-500/20 to-orange-500/20",
    themes: ["Dark & Moody", "Clean & Minimal", "Warm & Natural", "Bold & Editorial"],
  },
  creator: {
    id: "creator",
    name: "The Creator Hub",
    industry: "Influencer / Creator",
    price: "$799",
    originalPrice: "$1,099",
    description: "Creator site with media kit, brand deals page, and social links hub.",
    includes: [
      "Full custom setup with your branding",
      "Media kit page",
      "Brand partnerships section",
      "Social links hub",
      "Content showcase",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Sparkles,
    color: "from-fuchsia-500/20 to-pink-500/20",
    themes: ["Bold & Vibrant", "Clean & Modern", "Dark & Edgy", "Warm & Bright"],
  },
  portfolio: {
    id: "portfolio",
    name: "Folio Pro",
    industry: "Portfolio",
    price: "$799",
    originalPrice: "$1,099",
    description: "Clean developer or designer portfolio with project showcase and testimonials.",
    includes: [
      "Full custom setup with your branding",
      "Project showcase",
      "Skills section",
      "About me page",
      "Contact form",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Palette,
    color: "from-purple-500/20 to-pink-500/20",
    themes: ["Dark & Minimal", "Clean & Light", "Bold & Creative", "Warm & Earthy"],
  },
  marketing: {
    id: "marketing",
    name: "Amplify Agency",
    industry: "Marketing Agency",
    price: "$1,097",
    originalPrice: "$1,397",
    description: "Bold marketing agency site with case studies and client results.",
    includes: [
      "Full custom setup with your branding",
      "Case studies",
      "Services showcase",
      "Team profiles",
      "Client results",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: TrendingUp,
    color: "from-orange-500/20 to-amber-500/20",
    themes: ["Bold & Dark", "Clean & Modern", "Vibrant & Energetic", "Minimal & Sharp"],
  },
  recruitment: {
    id: "recruitment",
    name: "TalentBridge",
    industry: "Recruitment Agency",
    price: "$1,097",
    originalPrice: "$1,397",
    description: "Recruitment agency with job listings and candidate portal.",
    includes: [
      "Full custom setup with your branding",
      "Job listings",
      "Candidate portal",
      "Services page",
      "Team profiles",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Users,
    color: "from-blue-500/20 to-indigo-500/20",
    themes: ["Clean & Professional", "Dark & Bold", "Modern & Minimal", "Warm & Approachable"],
  },
  law: {
    id: "law",
    name: "Sterling Law Group",
    industry: "Law Firm",
    price: "$1,097",
    originalPrice: "$1,397",
    description: "Sophisticated law firm site with practice areas, attorney profiles, and consultation request form.",
    includes: [
      "Full custom setup with your branding",
      "Practice areas",
      "Attorney profiles",
      "Testimonials",
      "FAQ section",
      "Consultation request form",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Scale,
    color: "from-stone-500/20 to-neutral-500/20",
    themes: ["Classic Prestige", "Clean Minimal", "Modern Professional", "Sophisticated Dark"],
  },
  startup: {
    id: "startup",
    name: "Venture Launch",
    industry: "Startup",
    price: "$1,097",
    originalPrice: "$1,397",
    description: "Investor-ready startup site with pitch deck section and team profiles.",
    includes: [
      "Full custom setup with your branding",
      "Product pitch section",
      "Team profiles",
      "Investor info",
      "Roadmap display",
      "Domain & hosting setup",
      "SEO optimization",
      "30-day post-launch support",
    ],
    icon: Lightbulb,
    color: "from-violet-500/20 to-indigo-500/20",
    themes: ["Dark & Bold", "Clean & Modern", "Vibrant & Energetic", "Minimal & Sharp"],
  },
  ecommerce: {
  id: "ecommerce",
  name: "ShopFront",
  industry: "E-Commerce",
  price: "$1,297",
  originalPrice: "$1,697",
  description: "Ready-to-sell e-commerce brand site with product catalog and checkout.",
  requiresPayment: true,
  paymentNote: "Payment setup is included — full Shopify or WooCommerce store setup with checkout",
  includes: [
    "Full custom setup with your branding",
    "Product catalog",
    "Shopping cart",
    "Checkout integration ✓",
    "Customer reviews",
    "Category filtering",
    "Shopify or WooCommerce setup ✓",
    "Domain & hosting setup",
    "SEO optimization",
    "30-day post-launch support",
  ],
  icon: ShoppingBag,
  color: "from-pink-500/20 to-rose-500/20",
  themes: ["Clean & Modern", "Bold & Vibrant", "Dark & Premium", "Warm & Earthy"],
},

}


export default function OrderPage({
  params,
}: {
  params: { template: string }
}) {
  const template = templates[params.template]

  if (!template) {
    notFound()
  }

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <OrderForm template={template} />
      <Footer />
    </div>
  )
}

export function generateStaticParams() {
  return Object.keys(templates).map((id) => ({ template: id }))
}
